import {
  Box, Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  Container, Grid, GridItem, SimpleGrid
} from '@chakra-ui/react'
import AirbnbCard from 'components/AirbnbCard'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg='tomato' w='100%' paddingY={5} color='white' border={0}>
        This is the Box
        asdad lkjdasd

        alskd
      </Box>
      <div className={styles.main}>
        <Container maxW="full">
          <Box>
            <Breadcrumb>
              <BreadcrumbItem>
                <BreadcrumbLink href='#'>Home</BreadcrumbLink>
              </BreadcrumbItem>
            </Breadcrumb>
            <Box>
              {/* <SimpleGrid column={2}>
                <Box maxW="sm">
                  <AirbnbCard />
                </Box>
                <Box maxW="sm">
                  <AirbnbCard />
                </Box>
              </SimpleGrid> */}
              {/* <SimpleGrid columns={{ sm: 1, md: 2, lg: 4 }} spacing={2}>
                {
                  [1, 2, 4, 5, 6, 7, 8, 9, 10].map((_, idx) => (
                    <Box key={idx} height='auto' marginBottom={5}>
                      <AirbnbCard />
                    </Box>
                  ))
                }


              </SimpleGrid> */}
            </Box>
          </Box>
        </Container>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
